"use strict";

var backgound_loop_seconds = 1.5,
  obs_transition_seconds = 2.25,
  jump_transition_seconds = 0.7,
  cat_run_frame_current = 1,
  cat_run_frame_max = 6,
  cat_die_count = 0,
  cat_animation_interval = 100,
  high_score = 400,//400,
  score = 0,
  current_obs,
  is_jumping = false,
  is_dead = false,
  cat_interval,
  cat_die_interval,
  cat_hit_interval,
  base64string = "//uQZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAABPAAA5ywAFEhkgICYsMjc3PkRLUVFXW2NpaXN4f3+DiY6WlpmbnZ+foaOlpqaoqqysrrCys7O1t7m7u72/wMLCxMbIyMrMzc/P0dPV19fZ2tze3uDi5OTm5+nr6+3v8fPz9Pb4+vr8/v8AAAA8TEFNRTMuOThyBK8AAAAAAAAAADQgJAi4TQABzAAAOcu7qPbZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//twZAAAAAAAf4UAAAgAAA/woAABEx2Jp/lKAcGlMTW/ItA4AIAKAJAHALAIAoFAoFA4H8BIUDOo/A55UD7ZvA4S4Bhx4ocUf8G4AOejAwpn/AkDAzg4DAAAFBH/g2NhgMR+AcAC4T/8T4Dc8LhxYwtEDVn/+J8C4cQXFjC5gPkFg///Dbw+MWMNWCCgsAbeILix///+DYMCyAMYAHAwsjDGYWQBZAIIBZGFkf////4gmFkAXMCgAsjCyMUGASASAEAQASAOBgKBwMBQP5dC5vxH4B48uN5oYfiMBdwr/8eYVQYRH/xMxM0h4DCf/oDnHubkgh//mAjYw48ygPg8P//x5m5fQLhcHmXy////6BcNB5l83LhcUXy/////+Yj0KJcHuPcvqpekBgAwAwAwAgqSgSQ4rLzxkv/7wGQJAAWOYVD+YeSCjMxJ78w0AhzFiT/5ypBCU7Ep/zM0ELx4QZsqwwygqDpwKBaSfKbCRKCd9adu57DiJ02JRTD6M8dqiNA5zSYGcuqXJcdQiQ8i+O40qa71SqWR8voY6Qx0jmOR31dKyssjt+yzzNT3Gv/AgP4OZ7b7Wm5WXyXzEzvdpZtUja+fPPrz7iWeTw5tT7mxLO8f+V89na3zO1sf/l/ml+YmJ///8NTpQunbUh3///88k37+X///+TuoGmJhZFgEHEEETEJFIiQ0PR/KW97dmqKABcQ0Hdt0km8auG/uAjwN5Fi+cSH0OSyCIwo+kEimRCJyLJy6cPSiTSaopZ6fGFI5F506cOS4dPn5cKx04n72VSfZS689zmyCnq7brTz8/Pzk+Xi9Ol4vnpcOz3O585Upf9REIw+kYjlaX+eOn8uHP8Zp4Yx8+dbFBgAAAAAQAAkAAAAALAH8rCnmWxeWA6WC94cTTBQxM0jERM4/+002GyFgNgIblgCHlLIGoirDyhYgB3NpgYEGQeYPJEFBBSB2BSAazQYGExkFkfEBBQGBhMZgNIADCQSAcBAIAAQUGKLoYgguMUYsV8AINheYNlwsUx+lsfv4qxVYDwL4gwQYJpLYgIFmC0KDgYFGYDgKBgUZAYCGYRGYGE0GBiQZZLDfFBjfJUb/jejeEECKjfBgFgOAoDwIBncZgYSAgRCQGVBIBhICkvkrJT4oAb3/AwKEgMZAQVX//////+EQA+gbAZgIACgohOAAAAAOAP5XJ44I1R8PNYZpkcNOkjEk5YA1x8BEELmLZ1xcA2TxyghAb0HMGCIL9FDGAFi4guIJCdRBQYouhiJu8qh9S2ReJ5zstnf4qhV4gj5DSGnrIqdONoQTG2FDKFgDgclmQYlW9rJJON+IJiCAXGEpC7C1wSmW8syx9N/+IXGsKv///////CIKvwMTEBAB8AD7UlcH/uDp//uARAeBAp5A13dhoABXyBq+7DQACjD1W+wlUslIoKv5gx5QEkXKZ0zrK1cTuVhh0dwlxkbQiBkkqXS8bOoehkmikXz6C6a10na63T6/+h/+mR3qUkk43M3WoZP/9Y9zVVecHobfUXDYPAAEgAADgAP/0CP/WReQpdp3nKpotEiVSFLul4YxkbQFgOEeJdLxs6hMDJNFIvnzRdNa5w+enzp8v9f/Q/+px1epI2SSFdm63ES//6xhzVKvODCG31FxK/4gYgAAArG5Q4jiLv/2fJQVnKg2micmtixP7UpZJXuJqXti3PBEO254IkjPThNqCqHFZJ5myN9dv/+RiceY7UH4Hm9Swav/+o9EB+PiF/lCpw8FJkAgBfAg/13tk//GVDxJpto3TP/JrSQH9mKWgr1leXtm7kGCS1JAEIG8uLSg02bVmub67df/jcSjzDzFQbgWIr1Ihz//qNRo3xGHX0c4eKvVncACIAAAAAD/+5BkBAFT4ljUey+dmFXLGl9Nak8LwQlhzBm4IK6tKnhwFoQB7r7NxLA3lgq6i4HWu+37SGXv4/zVDInURqv9d29jgAG1g8W3JrtxkBZIACRpmq/h5q0/1ePsf7Sn2h4zPXn8jyfyx//+LoAAZNyLlvhBkPuWpZJ3CJCEP//x/AAOLH8fgAXCABCchYC5hO5b///////z556sAAAAAACAAHOC7BEEXUIwkyOw2RlH1QJDJZuqk8mD/Sl+TSWc111+NA4ZmLy//1///KiLGkxuEskegzxHD8d//oF0BX+oLpO/aIELQp///////xwdzwgFQDAQ8+/RQ//+X2SDnF30EYg6DZosChUXtXb2GbcQUiDqC9XoK9R+l2QZC6CANbg1i9rZJMwRZHxBIxO/L+v/64Qz070AnhS/Fg///GIR/yIML+cCiHh///7yqJwAAAAlhgA3wW/xGGKfBvlf6b/sRPk1/+MC+M4//Hf////////////jsPx6ffcFMAAQUAPfvozPzLL8UDARkfSSZ3G13RuSDq0DTWWFHe+BTF7ceu3/+3BkFIADR0HVcyxuACuHms8oZ8ANhSlb7CW4IL0lKzyWiLDaHZPJYpEVYW6qdvLAUViT4jREShsVF05jmBdCti/LhH1T3/OBNApsu5cPhO7fEcbf/8Yx/9ITLnc6Mwav///VHeIAAAAAMADAXAMBtg3zhaT8qW08cdqf36bBUDl1Yx/+v/5X/e36f///AfXfQMoIAAIgAHbuP+0xAmgS8wAT7gJPVPmIv7c42JCN0HSjN/DtwUuTThyQU1akpX3pKFqziwPLIzQI7BC4HDqfchco/tX50Tr87/jOAKxe54/F0YI7+JsXP/+Mwwf8K0t/KgHWPf//n//9ACvfBQEAAABAAJrAOCAfFhfCJ71r+/Igs//T3G/vrG///0Ef5f//////0//8b//QYr76BDAwABoABe78OOWm//uAZAcAAw9K1nsPbSA5Rgq/LQc+C01nW+wxVEDerOp80CtEoon5YGOJZY2q74Og9y8NsAu0kB3u7lSHU/GVPORC+9ZUOOdGREfjOb4ZAi3Sy+mVc0/mmP8zHYf//1g9mvrsVvV6x/b//qIT/rP/x2je///O//4pWewEQAAAAOAT66RuCqvBBtpdJ0Vx37BgIh9T9IjbfGx7L/+///xAVL9Czjdq+g4/+JL9/Jf7P/62336EoCIAAQAQ13Ufed93z8sKU7SwVKkFGY3RatN2ZVQNtK776TL8CGSOWOE6qs4RROo+1vPtMhyDTcx17coIUt/X+gKH9TVKf48//+Sf5b+VAKFv//////7ySM2gABAAAAQAHm6Q9hJXgExws/Pkkf2pIKGcjvNqv/MCo5/Vi7/BP/Lf45/////////////lipPVz/0qcQQAFmtB7tl24w7bQPLECqNOkvImzROTB1ns1B3/965FqdwiaN7/+3BkFIAC8lpX+wltACIB2s4oAmQNeW1T7DTZoM6YqzzIlIS7e6ZCgSBg+WfOhNiClU61U5HIowxGnvIn/GYPJ79ZBb9Q9f//iRLP5e/qEGE4///////52mu8AMgAABwAFFsuKAAwy5I7NsBYtT3daECF7q/v4r///1JjPkFZCIAAQAB92ZqARQRrX4XChxB60alGl3tmXZ7V7ic9NLb1/tPAC2TK5UEtuRNyJJei62obf2mpaWmlWh4i8fn5+tecLv+Wf4XMcqvyojX+VCu///KwmJb/Oln8qCV//////25SmVoIPLyt/QFlEgIVDIG1o/IgI3gqBoq8jnxhbbZAF8+6N9Et+q6m//+1P+P/Hj/9Xt9///66kiBCrvsaZyIAFSkh92X0eNTxjGgEBr3ADjAxiz7UxJlp//twZA8AAwdbVvsPang6iFqfDwUUC4FpWew9q6DinSo8mhSIaCeXja1jvoAPs8Z4kkFHtbpJGNHzC+75Jw3vb1nzxwxr+53+dEBL/0KiNr8zE6//84IAf/nT384Hv//////9ePjrPRe+AqgmCBghw9FgTqfp1TiAlWLvqLjdr+V2FtUMrI3/9OzqSv3/6P8Pxj4zw+P//+X/R/6g3///YWGT38DQpEABRCA34wh1masq8sCaMNESRjYgKZNF7tCyR+2Zd4h0BQpel2505xrm4hVG73pfZmS2z1bKU+v1KV+oKxJtXlm3nR4N//4XYgfzrfyeLZ//////9vkkeQ154E7KYEFFUj3EGjAYGYRSmA7niyGhoWGYWmihT6uz3af3t/6dfSn9f9H/2//+IBz29Rv//+/Dya78Bv/7gGQBgQMlWdZ7D1J4N6dqvxsFFAzxaVHMMbZhAa0p/PKJvGITAB4gAe5Zl7VFrlkFGzQh2x5pQzkjJAUMF2pEKpfLVrCLRAFZ3aDDakrDTRKm6PmDfPoE1yxdaZQuPSpQuSLHmR7fgaHC3LS5AOeWqUEL//8Menlf6hPFP//////l31H873iakLAEqVSO8D0GTxgsVXfQSBnIcULU/CgwKCofJ+9f0Vtaf6r77fq/9/6z///D/Gfi////cqZ3AcwNAAi5+OnKpvNCR2ZWxBCmv14Wx19qGLnpLtO6kYjEAAjAOjYmbTqXXpe5aG3hkeWS7oJk5C3Jyf3Th04cLx7+d/juAgZZz/GWePHuqD83//Ogn1/nS9/Og6D///////PznLx96vDiAEQAIAAHzLEjWUnVxGilMy59neZVyH/IYDOiHRWIjMamYq/1///6gDf3/SZv/+hL/Qv9Dt//////xoPgI1WN+glAEwAa//uAZAOAAxNDVfsMbRhUiypPPYpPC2FnW+e1WKDULOp8yCiEBAG1nDr9qGA4b4CpU3SgFtYZrsPvzzN0mpb3Up6aSuAIbKTyp7ZTPxETiFUS5XY9D4xHKXvOl8/W/PfU3+dBQkv3PT4wJ84qvhOf//UG63nHjpr84DIe///2JQtWwoQAQACIAD96P5kQ1PHwTssnF67Dz3Uy9MtSsB2Bc0re22bq7a/V2+80U/4jinl/iMOf6AAhpy72IWUpK8///xcMhz1HZbF/qIh//////+L8cjs9/BakSgAUSBPjKEo+YteA/sIPBDQAhTlMiZLt5XWq/mnTKlC1giqzR2dcsLw50anPet71RQ3mzot7I3c7//6gIIbc+0RX2wEv//gn/j/rxcE///5b///lJ3KPG7gEAAAAAJAbzoCh9G8cIgunU9evUSRylqd/M/X/p//8G8e//y+Lv////0///8E////j3yzN8Al0FgBMKAH/+4BkBIACnUJW+wlVEC3GGu8lpyMNNWdb7CW2YSOs6fzEHayu3atyG4n/7KAoIlTLKaQsBbpoi928PiMOt/PEhR5dJT2Cik1BuTYaTV2EygnoxivaYWfKf/+gC7+uJqU+FL//8af5n+K3///cWHT3g1y5mABYoA9wGkIRZxUHQNA9DwVlPTScxb1b///W3//+n+Dv/EP/////+/IVv6EoZKAAgJA3OXKd9XJU8p/iMIFI5D/v/IbEel7Qt4deiK34qMvS6q28az/0rJHbhkEkECFBayAXtfZeF7BTKY6+2cRs/3B0MzNUigQlo0V8Rb//+E72s1RntesqBYnvr/////3XRqUfe7AAYBAAAAAB23hcuKlZkpOzJgYmdQsSnf4oFYRG0vZ2S2dlanafRka+3Ns/3C9valreY///jm1moP7WorFvr/////likclULaz5BkBCAAwAgbV3UpcRPP2RtwRhcNYCEN0pMcXDWP/7gGQPAANBWVZ7LG0qPChKzyzKGQ2BK1PsvbSAwZPq/DecUGpPv4V4w6Y5CxShuZEwwJZdLBJJBi624X3wL4Y67k0zJLx8/jqt/f/hVx0fdVMcJayC/Fq///OhUP50hP86RAWf//////dTM0qK13qBoAEACeDYysCcinEPQFs7B96t2U5xIb/d/8635rNl1fy3/AMBMt1u7U+r//9Cb/Hhf8oPP//6CZuEov5BVABACAAhzfa8wpyWClGxUIUSWqux/Iq7ERrzqMsJtarYW6kOGdU0Gxbg9UjgH6nkPa4xWvK3SR7lQqXj56qVVNMhqnvdRT+rb6lgoSx1JMpnGp0u1Qwx7//nBOf2OofZY+C2dv/87//joz7ADAAABBkEekwQtUzwhkl9VfZv1Fz9H13+53drnGf/r/wUo0Hx+Q//9e///8mskq/5CGBgAC4AAfNifieCbgUDTAJA/nJ+UppvT9xKfA/o87r6wEIB//twZBMAAx9C13npbhgzZZrfICJVCn0JXew9S8DAJSt8sp18a/77qI2kwP106da+GMu7C9IFH+SbwaSRv6fQP7+m6z/x9BYGi38dhYrVUsWK3//yIN9vkm37CDG3u//8c9M9ygiCgAAIEQPLipLg5uXayZrbOuHZ/TR3tRF/+/3v6o34I/vRRbf0L1Pm7GNr9n//jXIrvwGYCAAM2AINdq23wLC/LB1F7zas9NFVITCYBevmGR/euBNjUpCg4r6pWlL6veiTS1mdEollu8iPts6oduXT+b7WBWFn8oT/ypf//oX/m/0E3/Re+wGYEAAAggcSuiSgfU1Tm2J/dvhZ/Y9ffv/9v/f/tMdfnF335V//+7r+sz///4dVDvkGUCAwOwAGP+A5tDNqvpvIYVV2wFSQLTZsaf23I//7YGQPgQKnQVZ7DFSwJoWKjjQC0AvdCVXnqbpAiYIrvAM8AO6z1HSB4MUw4F4lH/pzszHRQ/17JSi4VQKlgtSvjK7S+cpuS//+Dq/qIb/Hf/+gp/i7+Lm/0zfiCgCgAQABPj+gDRsSTjCb8s5zUeNlre339r/7f/Yza+I1/9v9Yb9gpAQCBkv1GpAM4VvDRAY26c1k624sHcBzU7NAtiVuACC1Y1LdqcY52vFOoKzQaWLoloamTKLleTeV9OpxlYyRUe5/6zwbQjSvWwWBq/x8Lf/b1EffrHHr3lRbI3pDv4EUEAyJAaAJDUSXKNqwtIHk1DwGyryqGdVVv6Ov36+zSmzVAv/7kGQBgAR5WdP7LTc4NOYazwXlAw2xCVvsJbTA8RYq/YMIqCAAAAAAAf8GwLEQ7LCeu8iYh143QoqCN0jtC8cMxa9IKll/DFCUgyCIR+XtPk0GLcVVVUg69e+mS2vUzX4Hr/JIE3u/9zVnu7e6S5eu25IfK5YVAPgvlZ6flgxgAHz/lsCwS0jf/4Fvz2ABwiSL5EAt//yfQQcmyHMIIdyZMnz9ZRZPfwQIAwGBAAMFz3gBAAAAAQYC8Q9AvDDW8YjfQc/6v2V//26/qroi+tv/x8dgOAQ/+M/9P/9QqpjmNpHUx+qu+AdAQABSAIeuahpNpyRovptK3Qp83wjDoQFk9Je51oy89Dc3dZi0DKxjcUiqPIW0ZAJDIrIwJJkQiAyheI03o3tsylacq1v061vfprISWz0R3ik6HqMmqntOaV9R0tdWhjuKHrzjfQfTskf5ue8wUAQAIBAIfu6BgoMXaw3ln7j/y7D0pJutAou71dmsljUNs7/2tU6f/f6fDjLylrtVfaV1f0r0PUr+Ys74A1AzAAIAAdoiS5pBKQoELv/7gGQJAAPUWlZ7DI04NqtKv2QnJQw1CVfNFbiA8KMq/PGc0Iauhim/Gou0CS0rTu0JiuJFjsQpqWmoa6NN3VWeMVRqXShokl4vZeQumJN5kqTI4Pv69dGuXrphinP/H9qSqkkxEQZWfXj7XPnzpgbF04XzxsbH86RA1/OA6fyVPT3/+3///n5w/Y6eav8QBwIAAIAAHzXIcgYCOVCEPTCk4AfKX9WStf9vvlbVa3/p//64r/6eyeifT/////////+Xy1d8AaAAgDAoQVBw8BqMsC4GSIESQC3jLYrYYDHqFqgAmCwuLWfz7JoYV1Et4zscsw+/Lhu4/0ivTNvCpTlBlspBBiWKRTWJlVX9khFb6qgAWBfmt5c/9f1Dx/TDoBab1Tp6O+wMgAAASIWArYSQxwGYLssiyBDU2ZtC/3Rf7oy/7vvRd6Jv7P+10/hcn/9mb9z7Md7zCVy8qXWNC/8rnPgGIAAACAAB8pc6//ugZAYAA+ta1XtPo9g7J+qvMeckDs1nV+0aeGmCLWk89NHksWTaTj9AOvlEhd67KSAfi7wnHdgC46VVNiyt2ElZGVoUpnPRSjkU46CWKudDGg5Hx1TzvnsOd95n5mpbpsyTXUWix9smSXlssZ8VwE4wDRwsk5LZFMaf//nxG/yxBoUDBJaJ/5ZLX//////z0+dc8dPzm+m0AEAAQAo2jiH5Wxvg5BsOycE7gpdRFV/OjlM/ZXP7Lb3/7/f/bdvtIC6vzv//dvrPCZxTyP///prPoEMAAAAAABqtDZn4SiL5WDdBGBsqZ89BzKeM/NpZKKupqEZaqTaskYmZiffeCVZ25qCMZW2yyNyjOD3zlI8clq72rjJlv9199HDx73nx0HzmdPxcoHmILpPz7nMef//OigJzVhC4A+Zel/57//////2Z2zAe03oAAAAAAAAD7eIVQkZp8Hsup8Ty7h+OTwOPSRfpU2tVqKJPVDaY6jgZ7nmGYty35czvnjp/W7+W7GbL1NLwFEguZrFteQX//1F+vJTFNHNRoff//////y2Wy0W8rEULSr/+CWACABwhwCplTwY2dsnmIUkag/6l7+RZ4s5IMwKS2rPy1mhgQMOhnINnDIRBETS6scQkGWzcU8eqNc+3/p/tAvR4/z///x/r7sOIAEy1e0tXffIOoAQAJgIjyi5D93y+//twRDEAApdCV3sIbFBe6FrPYY2ICkkJW+ehsslGoWr9gzaRnrskirG5rvch+n2txwQ4Kez07avb1o0Ejysx8IlLyGOxOOYlurWj5jsp+WnJTVosk69KtvvL+rRPQBBHipfz///x/r7sO4FaWr8////q1D7/7CIAGALUCQDcy+PQJuJomQUFhECAm0ICaaNrAIUBZpXd3t3BgIwq0tFSg6TmtRzWaYOhGKtU2o2a2r/rf+ThFv+s0/+/xwOr5NBhHiv6x9bnnfsJQAQAHAEgL/0MFLvLINlL6U6BJGVNiBbdXdRdQQ3DHvaXOcpmS6s4qlQovFOk2zlaipTRR2ym1G23/6z/8ahFm36zT//5IOr5iGk1/WYvXa/9F7AGEq6CMDHUGuQu9di7wAxu7BXzf2TP4/2tvClH3//7gEQQgAJzQtb7CDxAT0ha7z0nhgkk+1fsDVSBZazq/PGqlOkjnIGgBjNVtR/BJzRdrViILUs8Poctn/O/zRc1vQCz/ob//8Xln+4LQ+reOvO/aRwBAp3wOAZxHgGyPQh4MADuCpLUyS0LQtcVRIds/2hcjECYAmPGM4v2lWmlm5q5IDZmXPnEls7X53+wua28oCX9Df//k2/PASL6/HS87+AkoIgDcEABl9SVtkL7qJA170jQ2+9TloFLYmY8nxf/Hn/lxsNnXDImIajnDkgwwt3VkUGatl27/9P6CoGy/lBT//8q/9S/onfoEgwMAZSARsdsTJsAVyQAw0SBTPKxaox7RrbB4T+tLVfaMFxxociFDCFFsCcM0GGFu6xFpq2Xa7vX7oIzs7dAoAPfyg7//6hVP+8qCfzXIRYb///////KKp3/BHICAHdE0Df2KeKtPQ1DpRBBh5bUCRKBN1JKsFOfrv/juOtMvXap//tgZBSAAm5C1nsDVSIr5DqfBeIVC2FrVew9SaCwIGu8NRSkOlEA7cj3CCe28x+Qvrpj+n5AS/4Gn/oKf//ml/PoJIVG7bCDVe+0CQgMAHwCQDo3hjmELnVNvr1M3ZEz///tqtcYfBYPB/871v/zqEOEDupM3vgjACABMCAPruG7mBiEYvy4geayhSCTtqzEikrbO73btUF3vhtu2XjRBIJj3Z0qYfO9ChXr8ef4wbV6KKgA0scqJRxgEW//+Lg3amxyguv/GJn///////Fw5feCs8o4CbqzgQ1FQTwLFu3DxmbSuT/P9PeiW/X//X9qgYj/jX///HeOjfx9C/wGlgQArWmh//twZASAAt5DVnsIa+gvC0pvKAWhCu0PWewhsYCbBqs8J4iIv/Pi712OWDBUooxWCUuUrVctyt+oAnePaDdwGglrWU1CCIRDwNyixR2OVle1Sb+f9HpekONte7GQrn3sriCDc3/+qTgFN+ukofD63+iNrH///6gkAA0MCAJYAIfp8FZLkve3u+Ua3/59MbH43/+T/Vv9R///6fkXRvmpf//////8Lrv4GdiQQttLgNfSZOQtdUgG3TAF7EcZLE6LPGYlbrZ+dJ46IMBKGktUsIhBNikvQNkmW+8O01f/61c8f2EDRpK1KMx5WW/UDAl/t/pgV/XXHcztZPSIdM7/KEgNgHvksAuWPcnfDReYQ/vgQww9ns7ux1avm1dHkf+6up0bMAz6A1MmAHWOUD/wrv8suVFgM4bENf/7cGQKgAKsQ1X7DGrwIqE6zwFlBQxJa0/ssavgxS1qPAwIVCxPRwMI/Uieo771ZtOBZN60u5G44/P7L7LlodrTLZZJWu/rd3buPxpXQ50jMuhRwxEB7//5iDXqQXQk1m3dpmUg3vAlhXBAZEMBqGsFuATWXh52KvXIkU//qkPO+/qf//uQlAXzgDmBABIECP/xt9C5ZjOMrAiD/h4akKceg2LDy0xSqJmsGPa4rFk/ChGTU8nUX7ZxvFOWpNvopaFfui6v5mefpJLJAk2PumyKieC1BCur//nQOX9jJdvYxLn///////Kz4BngBwCAEIAwPSRTzKvJ0T1wIBH9Ncr/7f//TX9v///+Cfe/f/KMzX+/b////////jUKuAB2VACvSio/5ZG2UJjs4CDuwaPl6aR53KgJ/ov/+5BkDwADjVXS+wZsWEFqen8BYgdMSPlP4GBh6XYsKHzyjXxNRW3KsztJX+CvZZFGiiYMWkSqzZLIlEej/9KJ4SZz7ejOpX0lubabopGSRk9SDrGKE1Fq/+f/OB3LoyTh2i1bOk/7K/70j7KfdI9oorucdSDrNVBOUAGquT08imHZsaYPykKv6ozw7Ddao86qDjf+vbeqsVCvp/YurlykfO+DGf//+i+mRv6f9wZrK4K5+Qy3hhR2KgrMI6d2OS+2be/XlTd3OFTylwmr4wY7joTkUmuWKSaBEhcbowACfE4YN7HzEldr6kT8WSdhID4Zm46qOiozK7UGfapv0DNCPsfnhQGY+V2HKhXmjtmOTTcP79Nv1K6qer9pwaKl1RlWtVtR//Osw1pQCnAOJLnhGNYZGEIR0Y5wikeY9RBStt6f1Ca8W2cmtsPe5K22VJc8gpqEUu7ubnKm6V9u8tIrVMEZErjHczNaZWORZ2jApl0zp2IPX8ccDQi8dGVmMzeNy7ZIjRBUYgD4yiZGkhxlM0a7ChrNuz5qqqx7NqpcOgL/+1BkFAzC8CpSeg8ZyjYAui8AyQMD8AMoYAAAIHcAZQwAAAQmNt/VjeoCTH7L9+l3/9SUSQ0FhEhvWAmFia/xoLk02adziVg7vBvvxBBpp0oo76hoo6M8b8IIqlJGWH1/oEepwVALGlSKRUNRC6Ih4VCR6ODpLaHRh4Fp4NBUGhKWfViX//+7bltX/I8Ffh3f+xEj//51GvPCowcaPEolGkc7Yd5aKs6/rSWf5XT5Yf+xAD//8seFUYSSg0ODzyTYqWWKipHlXZ37UGnllUxB//sQZAEP8AAAf4AAAAgAAA/wAAABAAABpAAAACAAADSAAAAETUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBkIw/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGRFD/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZGcP8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBkiQ/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGSrD/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZM0P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk7w/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuOTguMlVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy45OC4yVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjk4LjJVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk/4/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGT/j/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZP+P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVBUEVUQUdFWNAHAABpAAAAAwAAAAAAAKAAAAAAAAAAAAsAAAAAAAAAVGl0bGUAa2l0dGVuIG1lb3cOAAAAAAAAAEFydGlzdABTb3VuZEJpYmxlLmNvbQUAAAAAAAAAR2VucmUAQmx1ZXNBUEVUQUdFWNAHAABpAAAAAwAAAAAAAIAAAAAAAAAAAFRBR2tpdHRlbiBtZW93AAAAAAAAAAAAAAAAAAAAAAAAAFNvdW5kQmlibGUuY29tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  base64string2 = "SUQzAwAAAAAzLVBSSVYAABGjAABYTVAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxMzIgNzkuMTU5MzMwLCAyMDE2LzA1LzA2LTAxOjEwOjU1ICAgICAgICAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6YmV4dD0iaHR0cDovL25zLmFkb2JlLmNvbS9id2YvYmV4dC8xLjAvIgogICAgeG1sbnM6eG1wRE09Imh0dHA6Ly9ucy5hZG9iZS5jb20veG1wLzEuMC9EeW5hbWljTWVkaWEvIgogICAgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIgogICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iCiAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIgogICAgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiCiAgICB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iCiAgIGJleHQ6b3JpZ2luYXRvcj0iUHJvIFRvb2xzIgogICBiZXh0Om9yaWdpbmF0b3JSZWZlcmVuY2U9ImlFckEwY2FkRGhvYWFhR2siCiAgIGJleHQ6b3JpZ2luYXRpb25EYXRlPSIyMDA5LTA4LTEzIgogICBiZXh0Om9yaWdpbmF0aW9uVGltZT0iMDQ6MjQ6MTciCiAgIGJleHQ6dGltZVJlZmVyZW5jZT0iMjMxMDQiCiAgIGJleHQ6dmVyc2lvbj0iMCIKICAgeG1wOk1ldGFkYXRhRGF0ZT0iMjAxNi0wNi0yOFQxOTozNToyMiswMjowMCIKICAgeG1wOk1vZGlmeURhdGU9IjIwMTYtMDYtMjhUMTk6MzU6MjIrMDI6MDAiCiAgIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MzgzOTQ0NmEtZmEzOS00NzhkLTk4M2MtYzU4MmVlMjY1N2E0IgogICB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjM4Mzk0NDZhLWZhMzktNDc4ZC05ODNjLWM1ODJlZTI2NTdhNCIKICAgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjU5Y2Q2Y2Q1LTRkNjQtNGNkNy1iNmQ2LTZlNWQ4ODQ1ODZjNSIKICAgZGM6Zm9ybWF0PSJhdWRpby9tcGVnIj4KICAgPHhtcERNOlRyYWNrcz4KICAgIDxyZGY6QmFnPgogICAgIDxyZGY6bGkKICAgICAgeG1wRE06dHJhY2tOYW1lPSJDdWVQb2ludCBNYXJrZXJzIgogICAgICB4bXBETTp0cmFja1R5cGU9IkN1ZSIKICAgICAgeG1wRE06ZnJhbWVSYXRlPSJmMTEwMjUiLz4KICAgICA8cmRmOmxpCiAgICAgIHhtcERNOnRyYWNrTmFtZT0iQ0QgVHJhY2sgTWFya2VycyIKICAgICAgeG1wRE06dHJhY2tUeXBlPSJUcmFjayIKICAgICAgeG1wRE06ZnJhbWVSYXRlPSJmMTEwMjUiLz4KICAgICA8cmRmOmxpCiAgICAgIHhtcERNOnRyYWNrTmFtZT0iU3ViY2xpcCBNYXJrZXJzIgogICAgICB4bXBETTp0cmFja1R5cGU9IkluT3V0IgogICAgICB4bXBETTpmcmFtZVJhdGU9ImYxMTAyNSIvPgogICAgPC9yZGY6QmFnPgogICA8L3htcERNOlRyYWNrcz4KICAgPHhtcE1NOkhpc3Rvcnk+CiAgICA8cmRmOlNlcT4KICAgICA8cmRmOmxpCiAgICAgIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiCiAgICAgIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6NTljZDZjZDUtNGQ2NC00Y2Q3LWI2ZDYtNmU1ZDg4NDU4NmM1IgogICAgICBzdEV2dDp3aGVuPSIyMDE2LTA2LTI4VDE5OjM1OjIyKzAyOjAwIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBBdWRpdGlvbiBDQyAyMDE1LjIgKE1hY2ludG9zaCkiCiAgICAgIHN0RXZ0OmNoYW5nZWQ9Ii9tZXRhZGF0YSIvPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJzYXZlZCIKICAgICAgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDozODM5NDQ2YS1mYTM5LTQ3OGQtOTgzYy1jNTgyZWUyNjU3YTQiCiAgICAgIHN0RXZ0OndoZW49IjIwMTYtMDYtMjhUMTk6MzU6MjIrMDI6MDAiCiAgICAgIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIEF1ZGl0aW9uIENDIDIwMTUuMiAoTWFjaW50b3NoKSIKICAgICAgc3RFdnQ6Y2hhbmdlZD0iLyIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgIDx4bXBNTTpEZXJpdmVkRnJvbQogICAgc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OWNkNmNkNS00ZDY0LTRjZDctYjZkNi02ZTVkODg0NTg2YzUiCiAgICBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjU5Y2Q2Y2Q1LTRkNjQtNGNkNy1iNmQ2LTZlNWQ4ODQ1ODZjNSIKICAgIHN0UmVmOm9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo1OWNkNmNkNS00ZDY0LTRjZDctYjZkNi02ZTVkODg0NTg2YzUiLz4KICA8L3JkZjpEZXNjcmlwdGlvbj4KIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAKPD94cGFja2V0IGVuZD0idyI/PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/jMMAAFNEqlj9GKACEAFaSkp7doiO93rXf/smnADC0/BiGWAAEFFOc8QD4fdCNU5G/nf9DneQhJw4KDQ+UBN4YLn/4Ygh5f84p39Z+IHAg7L/4kOd+Hy5/hj+oH/1OBAC0BLEAABQ+AAArWZZqlVVVpjUajVKYbch+0ftxdd7tEL2rdwSgi8FiJNiWQgOOcxNz6k96ZJim92XS6f/jIMAxEdB/DZePMAIPo/66KHvXd7UIPvl+vR/1/pf3bv/6AG20kspXs7zaYzNLZq/rhjRFMvFWil2qawMuM0WFmiqV6StTlZTfOKFUyWYKFxx7JO30v7pDt6X8t9Cn9r/63iv6XWpq/+MwwEQT8KcCX48YALRb+1n7kFNVFC/3JGG//bbkklyxHA6OAMvfmkfi4CEJok17FKP1hka4cggbpGX3WzT6jfIqFuA9WjDv3J9qW0z2t6N9LVdxBXVJUM11MR6ajwnJLtWbqFVk3JJZbbb4ZLVOPiNZcWbr6/7qD7CJVXmQspZ3fco0TVjawtC0f/8u0GFOCjQJQUES6iwGfvIB/+MgwIMSsDLZn8wAAIOtH6qhQqHS6gI60e6AGTLWJviMm2oNBri4FOi2MVpExt65VeJZbm509iURtuxySW22zw9AOC5uAm9R6dd+FUFCMMJEwILciJmRbZW2LQ6obTLfKZqKs4lh16P/4zDAkxjBMsW+eMaQqRWGZ/mQaWPqsk7XOxTV2htzsb4z74n1WyFfQ5SKZe9shhKXX8Nb837G/CYX6b///OW/X3+tQp//27v6KKcksltu223jIgUIZxTWhW8+YvzrdjVv1q1ZlVX54NS/NgzWlwE1P/yzHPY4XhVGCWTY7kRAImGtVWhLcuGzTv67Akx2YYEzwMLlYYKhoqE6AVv/4yDAvxr5nr2+YESVUg0swJR4o8RKDuIhgdfWCqUCJxJx79PfPHYNFazodiJqq///kkncB9nQyGlAiYg6trFcWvNNmIl8yTl+ked/JGiEMlN7f8sv84cMyiImXohI3f3czIkk8tS2N//jMMCuHMH2sl54xrS/m4cO4euMIRBCAgSAcseWWA4nC5MAAgYUKtfm0hcXAhwxGN9IHB8eIAw7oikDh//5cXNgKTlltt22//8n4Kqx5GEvaykp7/UrxQpmUlzMKC2CB2GiKNhj81JT4gbJm+MKAhTgLHmdUhLBma58shEv5KokKpfkXsKbz02Y99VUKFEiYzRhTBVwV3IIoFBRTf/jIMDKG5oetZZ4xrZZN/8tlCigoLff+vivJ//r7992T/+EvQTxd/qAJKVbkckktu1DAeB/MxasUSfOxf9LbwyCBn4bOYSTMirYYgkNFh+v5Zof8scjCoDeawGhqqVbLDPVrP9QwOH+/+MwwLYdml6qXmBGtUyw1I1ow8BB4DLAQkApUKgsSFAKytDNDFGhWWaPWRCSLAEagEMjHuffqa/QPULmerMgKScssttttu2FMQYxwTIGEfrAW40XT66tZamQioLAaDWqs0RClmW3H+XqVxjkqVz/kwEpMar/duUBICEqv6xqpRjwwEuzf/doal/hhRKeLA1UGqRLkbVjH9WVyrqn/+MgwM4cGgKeXmBGtPYJXHcS4i5Z4KlXbeudLPbiIryI//////////////////////////////////////////////////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAD/4zDAuBwpwnZeekaUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/4yDA1gyAAlwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRBRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  sound_object = new Audio("data:audio/mp3;base64," + base64string),
  sound_object2 = new Audio("data:audio/mp3;base64," + base64string2);

function init_game() {
  document.querySelector('.tubtime_panel').style.display = 'none';
  document.querySelector('.main_game_container').style.display = 'block';
  start_game();
}
function tubtime_panel_click() {
  init_game();
}
function hide_cat_run() {
  var i;
  for (i = 1; i < 6; i = i + 1) {
    document.querySelector('.game_cat_run_' + i).style.display = 'none';
  }
}
function hide_cat_jump() {
  document.querySelector('.game_cat_jump_1').style.display = 'none';
}
function hide_cat_die() {
  var i;
  for (i = 1; i < 10; i = i + 1) {
    document.querySelector('.game_cat_die_' + i).style.display = 'none';
  }
}
function jump_cat() {
  sound_object.play();
  is_jumping = true;
  clearInterval(cat_interval);
  hide_cat_run();
  document.querySelector('.game_cat_jump_1').style.display = 'block';
  TweenMax.fromTo('.game_cat', jump_transition_seconds,
		{top: '60%'},
		{ top: '30%', repeat: 1, yoyo: true, onComplete: jump_complete.bind(this) }
    );
}
function jump_complete() {
  is_jumping = false;
  document.querySelector('.game_cat_jump_1').style.display = 'none';
  update_run_cat();
  
  clearInterval(cat_interval);
  clearInterval(cat_hit_interval);

  cat_interval = setInterval(update_run_cat.bind(this), cat_animation_interval);
  cat_hit_interval = setInterval(check_hit.bind(this), cat_animation_interval);
}
function game_click_target_click() {
  if (is_jumping === true) {
    //console.log('already jumping');
  } else if (is_dead === true) {
    //console.log('already dead');
  } else{
    jump_cat();
  }
}

function start_cat() {
  clearInterval(cat_interval);
  clearInterval(cat_hit_interval);
  
  cat_interval = setInterval(update_run_cat.bind(this), cat_animation_interval);
  cat_hit_interval = setInterval(check_hit.bind(this), cat_animation_interval);
}
function check_hit(){
 // console.log('check_hit');
  score += 1;
  document.querySelector('.game_score_score' ).innerHTML = score;
  if(current_obs !== undefined){  

  var cat = (document.querySelector('.game_cat_hit' )),
      cat_style = window.getComputedStyle(cat),
      cat_width = Number(cat_style.width.split('px')[0]),
      cat_height = Number(cat_style.height.split('px')[0]),
      cat_x = Number(cat_style.left.split('px')[0]),
      cat_y = 0,//Number(cat_style.top.split('px')[0]),
      obs_style = window.getComputedStyle(current_obs),
      obs_width = Number(obs_style.width.split('px')[0]),
      obs_height = Number(obs_style.height.split('px')[0]),
      obs_x = Number(obs_style.left.split('px')[0])+120,
      obs_y = 0,//Number(obs_style.top.split('px')[0]),
      rect1 = {x: cat_x, y: cat_y, width: cat_width, height: cat_height},
      rect2 = {x: obs_x, y: obs_y, width: (obs_width*0.75), height: obs_height},
      w = window,
      d = document,
      e = d.documentElement,
      g = d.getElementsByTagName('body')[0],
      width = w.innerWidth || e.clientWidth || g.clientWidth,  // the width
      height = w.innerHeight || e.clientHeight || g.clientHeight;  // the width

    if (cat_style.left.indexOf("%") > -1) {
      cat_x = cat_style.left.substr(0, cat_style.left.length - 1);   // get the `10`
      cat_x = parseInt(cat_x, 10);  // convert to number
      cat_x = ((cat_x * width) / 100);  // alert (percent * width / 100)
      
      obs_x = obs_style.left.substr(0, obs_style.left.length - 1);   // get the `10`
      obs_x = parseInt(obs_x, 10);  // convert to number
      obs_x = ((obs_x * width) / 100);  // alert (percent * width / 100)
    } 
    
    rect1 = {x: cat_x, y: 0, width: cat_width, height: cat_height};
    rect2 = {x: obs_x, y: 0, width: (obs_width*0.75), height: obs_height};
    
    if ((rect1.x < (rect2.x + rect2.width)) && ((rect1.x + rect1.width) > rect2.x) && (rect1.y < (rect2.y + rect2.height)) && ((rect1.height + rect1.y) > rect2.y)) {
      if(current_obs === document.querySelector(".game_table")) {
        if(is_jumping !== false){
          on_hit();
        }
      }else{
        if(is_jumping !== true) {
          on_hit();
        }
      }
    }
  }
  
  if(score > high_score){
    on_win();
  }
}
function on_win(){
  clearInterval(cat_interval);
  clearInterval(cat_hit_interval);
  
  TweenMax.killTweensOf(document.querySelector(".game_cat"));

  TweenMax.killTweensOf(current_obs);
  TweenMax.killTweensOf(document.querySelector(".main_game_wall_1"));
  TweenMax.killTweensOf(document.querySelector(".main_game_wall_2"));
  
  hide_cat_run();
  hide_cat_jump();
  
  document.querySelector('.game_win').style.display = 'block';
}
function on_hit() {
  if(is_dead === false){
    clearInterval(cat_interval);
    clearInterval(cat_hit_interval);
    
    sound_object2.play();
    
    is_dead = true;

    TweenMax.killTweensOf(document.querySelector(".game_cat"));

    TweenMax.killTweensOf(current_obs);
    TweenMax.killTweensOf(document.querySelector(".main_game_wall_1"));
    TweenMax.killTweensOf(document.querySelector(".main_game_wall_2"));

    hide_cat_run();
    hide_cat_jump();

    cat_die_count = 1;
    document.querySelector('.game_cat_die_' + cat_die_count).style.display = 'block';
    cat_die_interval = setInterval(update_die_cat, cat_animation_interval);

    TweenMax.to(document.querySelector(".game_cat"), 0.5, {left: '10%',  ease: Linear.easeNone});
  }
}
function update_die_cat() {
  cat_die_count = cat_die_count + 1;
  if(cat_die_count < 10){
      document.querySelector('.game_cat_die_' + cat_die_count).style.display = 'block';
      document.querySelector('.game_cat_die_' + (cat_die_count-1)).style.display = 'none';
  }else{
    clearInterval(cat_die_interval);
    document.querySelector('.game_lose').style.display = 'block';
  }
}
function update_run_cat() {
  document.querySelector('.game_cat_run_' + cat_run_frame_current).style.display = 'none';
  cat_run_frame_current = cat_run_frame_current + 1;
  if(cat_run_frame_current === cat_run_frame_max){
    cat_run_frame_current = 1;
  }
  document.querySelector('.game_cat_run_'+cat_run_frame_current).style.display = 'block';
}
function loop_background() {
  TweenMax.set(document.querySelector(".main_game_wall_1"),  {left: '0%', ease: Linear.easeNone});
  TweenMax.to(document.querySelector(".main_game_wall_1"), backgound_loop_seconds, {left: '-100%', ease: Linear.easeNone});
  
  TweenMax.set(document.querySelector(".main_game_wall_2"),  {left: '100%', ease: Linear.easeNone});
  TweenMax.to(document.querySelector(".main_game_wall_2"), backgound_loop_seconds, {left: '0%', ease: Linear.easeNone, onComplete:loop_background});
}
function launch_obstacle(){
  if(is_dead === false){
    var rand = Math.random();

    if(rand < (0.166*1)){
      current_obs = document.querySelector(".game_plant");
    } else if(rand < (0.166*2)){
      current_obs = document.querySelector(".game_bin");} 
    else if(rand < (0.166*3)){
      current_obs = document.querySelector(".game_box");} 
    else if(rand < (0.166*4)){
      current_obs = document.querySelector(".game_bag");
    } else if(rand < (0.166*5)){
      current_obs = document.querySelector(".game_briefcase");
    } else {
      current_obs = document.querySelector(".game_table");
    }

    TweenMax.set(current_obs,  {left: '100%', display:'block', ease: Linear.easeNone});
    TweenMax.to(current_obs, obs_transition_seconds, {left: '-50%', ease: Linear.easeNone, onComplete:launch_obstacle});
  }
}
function start_obstacles() {
  setTimeout(launch_obstacle.bind(this), 1500);
}
function start_game() {
  score = 0;
  loop_background();
  start_cat();
  start_obstacles();
}
function game_lose_click(){
  document.querySelector('.game_lose').style.display = 'none';
  document.querySelector('.game_win').style.display = 'none';
  document.querySelector('.game_goodluck').style.display = 'none';
  document.querySelector(".game_bin").style.left = '100%';
  document.querySelector(".game_box").style.left = '100%';
  document.querySelector(".game_bag").style.left = '100%';
  document.querySelector(".game_plant").style.left = '100%';
  document.querySelector(".game_briefcase").style.left = '100%';
  document.querySelector(".game_table").style.left = '100%';
  document.querySelector(".game_cat").style.top = '60%';
  document.querySelector(".game_cat").style.left = '15%';
  is_dead = false;
  is_jumping = false;
  hide_cat_die();
  start_game();
}
function game_tc_click() {
  document.querySelector('.game_tc').style.display = 'none';
}
function game_tc_btn_click() {
  document.querySelector('.game_tc').style.display = 'block';
}
function game_tick1_btn_click(){
  if(document.querySelector('.game_tick1_btn').style.opacity === '1'){
    document.querySelector('.game_tick1_btn').style.opacity = '0';
  }else{
    document.querySelector('.game_tick1_btn').style.opacity = '1';
  }
}
function game_tick2_btn_click(){
  if(document.querySelector('.game_tick2_btn').style.opacity === '1'){
    document.querySelector('.game_tick2_btn').style.opacity = '0';
  }else{
    document.querySelector('.game_tick2_btn').style.opacity = '1';
  }
}
function game_enter_btn_click(){
  var a = (document.querySelector(".game_tick1_btn").style.opacity === '1'),
    b = (document.querySelector(".game_tick2_btn").style.opacity === '1');
  
  if( a && b){
    document.querySelector(".game_form").submit();
  }
  //
  //document.querySelector('.game_goodluck').style.display = 'block';
}
var app = {
    add_listners : function () {
      document.querySelector('.tubtime_panel').addEventListener('click', tubtime_panel_click.bind(this));
      document.querySelector('.game_click_target').addEventListener('click', game_click_target_click.bind(this));
      document.querySelector('.game_lose').addEventListener('click', game_lose_click.bind(this));
      //document.querySelector('.game_goodluck').addEventListener('click', game_lose_click.bind(this));
      document.querySelector('.game_tc').addEventListener('click', game_tc_click.bind(this));
      document.querySelector('.game_tc_btn').addEventListener('click', game_tc_btn_click.bind(this));
      document.querySelector('.game_tick1_btn').addEventListener('click', game_tick1_btn_click.bind(this));
      document.querySelector('.game_tick2_btn').addEventListener('click', game_tick2_btn_click.bind(this));
      document.querySelector('.game_enter_btn').addEventListener('click', game_enter_btn_click.bind(this));
    }
  };
function init_site() {
  app.add_listners();
}
window.addEventListener("load", init_site);